### PR TITLE
Make request.pipe() accessible for streaming

### PR DESCRIPTION
**Pull request by adam-nielsen**
I needed to download some files from an NTLM server and because of their size, streaming was the only practical solution.

I have hacked in support for this so I'm passing it along in case you want to include it.  Feel free to reimplement in a different way if you have any better ideas how to achieve the same thing.

### CODE REVIEW

**Comment by FrankyBoy** [comment]
Thanks, I'll push the version and publish tomorrow (because frankly, I didn't do anything with node in ages, so it will probably take a little to re-familiarize myself with everything)

**Comment by adam-nielsen** [comment]
No worries, many thanks!

**Comment by FrankyBoy** [comment]
Whew, just two weeks after I said I'd do it I actually did. 0.1.4 @ npm. Super sorry for the delay.

**Comment by adam-nielsen** [comment]
No worries at all, thanks! :-)

**Pull request merged**
