### PR TITLE
Upgrade agentkeepalive dependency for node 0.12

### PR DESCRIPTION
**Pull request by garthkerr**
This will fix compatibility with 0.12 and still works with 0.10

### CODE REVIEW

**Comment by saadtazi** [comment]
+1

**Comment by FrankyBoy** [comment]
nice, thx ... now I just need to remember how to even publish this ;)

**Comment by FrankyBoy** [comment]
... and published to npmjs. Cheers!

**Comment by garthkerr** [comment]
Thanks for the quick merge!

**Pull request merged**
